## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Mackenzie Webster, PhD"
theme = "hugo-story"
publishDir = "docs"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "I am a cognitive psychologist studying primate social behavior and cognition. I am currently a Postdoctoral Fellow in Research & Science Teaching (FIRST) at Emory University."
  logo = "images/banner.jpg"
  favicon = false

[Params.social]
  # github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/mackfwebster"
  email = "mackenzie.f.webster@gmail.com"
  # instagram = "https://instagram.com"
  # linkedin = "https://linkedin.com"
  # telegram = "https://telegram.org"