## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Mackenzie Webster, PhD"
theme = "hugo-story"
publishDir = "docs"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  favicon = false

[Params.social]
  twitter = "https://twitter.com/mackfwebster"
  email = "mackenzie.f.webster@gmail.com"
